//! Exports.
//!
//! These are conveniences, not interchange formats. Mermaid and DOT both
//! re-lay-out, so they throw away the geometry the model actually stores —
//! useful for a quick picture in a chat window, wrong for anything that has to
//! match the diagram someone drew. `amcli view render` is the faithful path.

use std::collections::HashMap;

use amcli_graph::Graph;
use amcli_model::{ConceptKind, Model};

use crate::output::{CliError, Code, Output, Row};

pub fn run(g: &Graph<'_>, format: &str, out_path: Option<&str>) -> Result<Output, CliError> {
    let m = g.model();
    let body = match format {
        "csv" => csv(m),
        "mermaid" => mermaid(m),
        "dot" => dot(m),
        "json" => json(g),
        other => {
            return Err(CliError::new(
                Code::Unsupported,
                "unsupported",
                format!("`{other}` is not an export format"),
            )
            .hint("csv, json, mermaid or dot; for a faithful picture use `amcli view render`"));
        }
    };

    match out_path {
        Some(p) => {
            std::fs::write(p, &body)
                .map_err(|e| CliError::new(Code::Io, "io", format!("`{p}`: {e}")))?;
            Ok(Output::one(Row::new().s("path", p.to_string()).n("bytes", body.len() as i64)))
        }
        None => {
            print!("{body}");
            Ok(Output::empty())
        }
    }
}

fn csv(m: &Model) -> String {
    let mut s = String::from("id,type,name,layer,folder,source,target,documentation\n");
    for c in m.concepts() {
        let cells = [
            c.id.clone(),
            c.kind.name().to_string(),
            c.name.clone(),
            c.kind.layer().map(|l| l.as_str().to_string()).unwrap_or_default(),
            m.folder_path_of(c).to_string(),
            c.source.clone().unwrap_or_default(),
            c.target.clone().unwrap_or_default(),
            m.documentation(c.node).unwrap_or_default(),
        ];
        s.push_str(&cells.iter().map(|v| quote_csv(v)).collect::<Vec<_>>().join(","));
        s.push('\n');
    }
    s
}

fn quote_csv(v: &str) -> String {
    if v.contains([',', '"', '\n']) {
        format!("\"{}\"", v.replace('"', "\"\""))
    } else {
        v.to_string()
    }
}

/// Mermaid's arrow vocabulary is much smaller than ArchiMate's, so several
/// relationship types necessarily render the same. The collision is documented
/// in the header rather than hidden.
fn mermaid(m: &Model) -> String {
    use amcli_model::RelType::*;
    let mut s = String::from(
        "%% Generated by amcli. Mermaid re-lays-out, so this is not the diagram\n\
         %% anyone drew; use `amcli view render` for that. Mermaid has fewer arrow\n\
         %% styles than ArchiMate, so Composition/Aggregation and\n\
         %% Serving/Triggering each collapse to one glyph.\n\
         flowchart TD\n",
    );
    let mut names: HashMap<&str, String> = HashMap::new();
    for c in m.concepts() {
        if c.kind.is_relationship() {
            continue;
        }
        let key = sanitize(&c.id);
        names.insert(c.id.as_str(), key.clone());
        let label = c.name.replace(['"', '[', ']', '(', ')', '{', '}', '<', '>', ';', '#'], " ");
        // Behaviour elements get the rounded shape, matching the notation.
        let rounded = matches!(&c.kind, ConceptKind::Element(e)
            if amcli_view::notation::figure_of(*e) == amcli_view::Figure::RoundedRect);
        let (open, close) = if rounded { ("(\"", "\")") } else { ("[\"", "\"]") };
        s.push_str(&format!("  {key}{open}{label}{close}\n"));
    }
    for c in m.concepts() {
        let ConceptKind::Relationship(r) = &c.kind else { continue };
        let (Some(src), Some(tgt)) = (c.source.as_deref(), c.target.as_deref()) else { continue };
        let (Some(a), Some(b)) = (names.get(src), names.get(tgt)) else { continue };
        let arrow = match r {
            Composition | Aggregation => "---",
            Realization | Specialization => "-.->",
            Access | Influence => "-.->",
            Association => "---",
            _ => "-->",
        };
        s.push_str(&format!("  {a} {arrow}|{}| {b}\n", r.info().short));
    }
    s
}

fn dot(m: &Model) -> String {
    use amcli_model::RelType::*;
    let mut s = String::from(
        "// Generated by amcli. Graphviz re-lays-out; `amcli view render` keeps\n\
         // the geometry the model stores.\ndigraph model {\n  rankdir=TB;\n  node [shape=box];\n",
    );
    for c in m.concepts() {
        if c.kind.is_relationship() {
            continue;
        }
        s.push_str(&format!("  \"{}\" [label=\"{}\"];\n", c.id, c.name.replace('"', "'")));
    }
    for c in m.concepts() {
        let ConceptKind::Relationship(r) = &c.kind else { continue };
        let (Some(src), Some(tgt)) = (c.source.as_deref(), c.target.as_deref()) else { continue };
        let style = match r {
            Composition => "arrowtail=diamond, dir=back",
            Aggregation => "arrowtail=odiamond, dir=back",
            Realization => "style=dashed, arrowhead=onormal",
            Specialization => "arrowhead=onormal",
            Serving => "arrowhead=vee",
            Access => "style=dotted, arrowhead=vee",
            Influence => "style=dashed, arrowhead=vee",
            Flow => "style=dashed",
            Association => "arrowhead=none",
            _ => "",
        };
        s.push_str(&format!("  \"{src}\" -> \"{tgt}\" [label=\"{}\", {style}];\n", r.info().short));
    }
    s.push_str("}\n");
    s
}

fn json(g: &Graph<'_>) -> String {
    let m = g.model();
    let mut s = String::from("{\n  \"concepts\": [\n");
    let mut first = true;
    for (id, c) in m.concepts_with_ids() {
        if !first {
            s.push_str(",\n");
        }
        first = false;
        let (i, o) = g.degree(id);
        s.push_str(&format!(
            "    {{\"id\":{},\"type\":{},\"name\":{},\"folder\":{},\"in\":{i},\"out\":{o}{}}}",
            crate::output::quote(&c.id),
            crate::output::quote(c.kind.name()),
            crate::output::quote(&c.name),
            crate::output::quote(m.folder_path_of(c)),
            match (&c.source, &c.target) {
                (Some(a), Some(b)) => format!(
                    ",\"source\":{},\"target\":{}",
                    crate::output::quote(a),
                    crate::output::quote(b)
                ),
                _ => String::new(),
            }
        ));
    }
    s.push_str("\n  ]\n}\n");
    s
}

fn sanitize(id: &str) -> String {
    let mut out: String =
        id.chars().map(|c| if c.is_ascii_alphanumeric() { c } else { '_' }).collect();
    // A leading digit is not a legal Mermaid node id.
    if out.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        out.insert(0, 'n');
    }
    out
}
